export const CORE_BLOCKS = new Set<string>([
	'Basic Latin',
	'Latin-1 Supplement',
	'Latin Extended-A',
	'Latin Extended-B',
	'IPA Extensions',
	'Spacing Modifier Letters',
	'Combining Diacritical Marks',
	'Greek and Coptic',
	'Combining Diacritical Marks Supplement',
	'Latin Extended Additional',
	'Greek Extended',
	'General Punctuation',
	'Superscripts and Subscripts',
	'Currency Symbols',
	'Combining Diacritical Marks for Symbols',
	'Letterlike Symbols',
	'Number Forms',
	'Arrows',
	'Mathematical Operators',
	'Miscellaneous Technical',
	'Geometric Shapes',
	'Miscellaneous Symbols',
	'Dingbats',
	'Miscellaneous Mathematical Symbols-A',
	'Supplemental Arrows-A',
	'Supplemental Arrows-B',
	'Miscellaneous Mathematical Symbols-B',
	'Supplemental Mathematical Operators',
	'Variation Selectors',
	'Mathematical Alphanumeric Symbols',
	'Miscellaneous Symbols and Arrows',
	'Miscellaneous Symbols and Pictographs',
	'Emoticons',
	'Transport and Map Symbols',
]);

export const EXTRA_BLOCKS = new Set<string>([
	'Latin Extended-C',
	'Latin Extended-D',
	'Latin Extended-E',
	'Latin Extended-F',
	'Latin Extended-G',
	'Cyrillic',
	'Cyrillic Supplement',
	'Hebrew',
	'Arabic',
	'Arabic Supplement',
	'Arabic Extended-A',
	'Arabic Extended-B',
	'Arabic Extended-C',
	'Arabic Presentation Forms-A',
	'Arabic Presentation Forms-B',
	'Armenian',
	'Georgian',
	'Georgian Extended',
	'Georgian Supplement',
	'Hangul Jamo',
	'Hiragana',
	'Katakana',
	'Enclosed Alphanumerics',
	'Box Drawing',
	'Block Elements',
]);

export const ALLOWED_BLOCKS = new Set([...CORE_BLOCKS, ...EXTRA_BLOCKS]);

export const CORE_CATEGORIES = [
	'modifier',
	'combining',
	'latin',
	'greek',
	'punctuation',
	'math_operators',
	'math_number',
	'math_alphanumerics',
	'currency',
	'emoji',
	'misc',
	'format',
];

export const latinPrefixLetters = 'abcdefghijklmnopqrstuvwxyz'.split('');
