#!/usr/bin/env tsx

// invocation: npm run generate:intro

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import {fileURLToPath} from 'node:url';
import Markfive from 'markfive';

function fail(msg: string): never {
	console.error(msg);
	process.exit(1);
}

function escapeTSString(s: string): string {
	return s.replace(/\\/g, '\\\\').replace(/'/g, '\\\'').replace(/\n/g, '\\n');
}

function main() {
	const __dirname = path.dirname(fileURLToPath(import.meta.url));
	const projectRoot = path.resolve(__dirname, '..');
	const introPath = path.join(projectRoot, 'content', 'intro.mf');

	if (!fs.existsSync(introPath)) {
		fail(`intro.mf not found at ${introPath}`);
	}

	const source = fs.readFileSync(introPath, 'utf8');
	const html = new Markfive(source).run();

	const lines = [
		'// This file is auto-generated by scripts/generate-intro.ts',
		'// Do not edit this file directly.\n',
		`export const introHtml = '${escapeTSString(html)}';\n`,
	];

	const srcDir = path.join(projectRoot, 'src', 'content');
	if (!fs.existsSync(srcDir)) {
		fs.mkdirSync(srcDir, {recursive: true});
	}

	fs.writeFileSync(path.join(srcDir, 'intro.generated.ts'), lines.join('\n'), 'utf8');
	console.log('Generated src/content/intro.generated.ts');
}

main();
