#!/usr/bin/env tsx

// invocation: npm run generate:assigned-ranges

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import {fileURLToPath} from 'node:url';

function fail(msg: string): never {
	console.error(msg);
	process.exit(1);
}

function loadUnicodeData(unicodePath: string): Set<number> {
	const content = fs.readFileSync(unicodePath, 'utf8');
	const set = new Set<number>();
	// UnicodeData.txt: semicolon-separated; field 0 = code point (hex)
	for (const line of content.split(/\r?\n/)) {
		if (!line) continue;
		const parts = line.split(';');
		if (parts.length < 1) continue;
		const cpHex = parts[0];
		const cp = parseInt(cpHex, 16);
		if (Number.isFinite(cp)) {
			set.add(cp);
		}
	}
	return set;
}

type BlockRange = {start: number; end: number; name: string};

function loadBlocks(blocksPath: string): BlockRange[] {
	const content = fs.readFileSync(blocksPath, 'utf8');
	const ranges: BlockRange[] = [];
	for (const line of content.split(/\r?\n/)) {
		if (!line || line.startsWith('#')) continue;
		const m = line.match(/^([0-9A-Fa-f]{4,6})(?:\.\.([0-9A-Fa-f]{4,6}))?;\s*(.+)$/);
		if (!m) continue;
		const start = parseInt(m[1], 16);
		const end = m[2] ? parseInt(m[2], 16) : start;
		const name = m[3].trim();
		ranges.push({start, end, name});
	}
	return ranges;
}

function codePointsToRanges(codePoints: number[]): [number, number][] {
	if (codePoints.length === 0) return [];

	codePoints.sort((a, b) => a - b);

	const ranges: [number, number][] = [];
	let rangeStart = codePoints[0];
	let prevCp = codePoints[0];

	for (let i = 1; i < codePoints.length; i++) {
		const cp = codePoints[i];
		if (cp === prevCp + 1) {
			// Continue the current range
			prevCp = cp;
		} else {
			// End the current range and start a new one
			ranges.push([rangeStart, prevCp]);
			rangeStart = cp;
			prevCp = cp;
		}
	}

	// Add the final range
	ranges.push([rangeStart, prevCp]);

	return ranges;
}

function generateAssignedRangesFile(
	blockRanges: BlockRange[],
	assignedCodePoints: Set<number>,
): string {
	const lines: string[] = [];

	// Add header
	lines.push('// This file is auto-generated by scripts/generate-assigned-ranges.ts');
	lines.push('// Do not edit this file directly.\n');
	lines.push('export const assignedRanges: [string, [number, number][]][] = [');

	// Sort blocks by starting code point
	const sortedBlocks = [...blockRanges].sort((a, b) => a.start - b.start);

	for (const {start, end, name: blockName} of sortedBlocks) {
		if (blockName.startsWith('<')) continue;

		// Find all assigned code points within this block
		const blockCodePoints: number[] = [];
		for (let cp = start; cp <= end; cp++) {
			if (assignedCodePoints.has(cp)) {
				blockCodePoints.push(cp);
			}
		}

		// Skip blocks with no assigned code points
		if (blockCodePoints.length === 0) continue;

		// Convert to ranges
		const ranges = codePointsToRanges(blockCodePoints);

		// Convert to hex format
		const hexRanges = ranges.map(([rangeStart, rangeEnd]) => `[0x${rangeStart.toString(16).toUpperCase().padStart(4, '0')}, 0x${rangeEnd.toString(16).toUpperCase().padStart(4, '0')}]`);

		lines.push(`\t['${blockName}', [${hexRanges.join(', ')}]],`);
	}

	lines.push('];\n');

	return lines.join('\n');
}

function main() {
	const __dirname = path.dirname(fileURLToPath(import.meta.url));
	const projectRoot = path.resolve(__dirname, '..');
	const unicodePath = path.join(projectRoot, 'data', 'UnicodeData.txt');
	const blocksPath = path.join(projectRoot, 'data', 'Blocks.txt');

	if (!fs.existsSync(unicodePath)) {
		fail(`UnicodeData.txt not found at ${unicodePath}`);
	}
	if (!fs.existsSync(blocksPath)) {
		fail(`Blocks.txt not found at ${blocksPath}`);
	}

	const assignedCodePoints = loadUnicodeData(unicodePath);
	const blockRanges = loadBlocks(blocksPath);

	const content = generateAssignedRangesFile(blockRanges, assignedCodePoints);

	const srcDir = path.join(projectRoot, 'src', 'data');
	if (!fs.existsSync(srcDir)) {
		fs.mkdirSync(srcDir, {recursive: true});
	}

	fs.writeFileSync(path.join(srcDir, 'assigned-ranges.ts'), content, 'utf8');
	console.log('Generated src/data/assigned-ranges.ts');
}

main();
