// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

import {STROKE, HOOK} from '../constants/strings';
import {_, C, S} from '../constants/strings';
import {ML, LL} from '../constants/strings';

const latin_extendedc: NameEntry[] = [
	{cp: 0x2C60, end: 'L WITH DOUBLE BAR', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C61, end: 'L WITH DOUBLE BAR', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C62, end: 'L WITH MIDDLE TILDE', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C63, template: [LL, C, 'P', STROKE], cat: 'Lu'},
	{cp: 0x2C64, end: 'R WITH TAIL', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C65, template: [LL, S, 'A', STROKE], cat: 'Ll'},
	{cp: 0x2C66, end: 'T WITH DIAGONAL STROKE', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C67, end: 'H WITH DESCENDER', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C68, end: 'H WITH DESCENDER', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C69, end: 'K WITH DESCENDER', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C6A, end: 'K WITH DESCENDER', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C6B, end: 'Z WITH DESCENDER', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C6C, end: 'Z WITH DESCENDER', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C6D, end: 'ALPHA', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C6E, template: [LL, C, 'M', HOOK], cat: 'Lu'},
	{cp: 0x2C6F, end: 'TURNED A', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C70, end: 'TURNED ALPHA', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C71, end: 'V WITH RIGHT HOOK', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C72, template: [LL, C, 'W', HOOK], cat: 'Lu'},
	{cp: 0x2C73, template: [LL, S, 'W', HOOK], cat: 'Ll'},
	{cp: 0x2C74, end: 'V WITH CURL', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C75, end: 'HALF H', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C76, end: 'HALF H', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C77, end: 'TAILLESS PHI', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C78, end: 'E WITH NOTCH', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C79, end: 'TURNED R WITH TAIL', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C7A, end: 'O WITH LOW RING INSIDE', template: [LL, S], cat: 'Ll'},
	{cp: 0x2C7B, end: 'SMALL CAPITAL TURNED E', template: [LL, _], cat: 'Ll'},
	{cp: 0x2C7C, name: 'LATIN SUBSCRIPT SMALL LETTER J', cat: 'Lm'},
	{cp: 0x2C7D, template: [ML, 'CAPITAL V'], cat: 'Lm'},
	{cp: 0x2C7E, end: 'S WITH SWASH TAIL', template: [LL, C], cat: 'Lu'},
	{cp: 0x2C7F, end: 'Z WITH SWASH TAIL', template: [LL, C], cat: 'Lu'},
];

export const characters: Record<string, NameEntry[]> = {latin_extendedc};
