// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

import {DESCENDER} from '../constants/strings';
import {C, S} from '../constants/strings';
import {CL} from '../constants/strings';

const cyrillic: NameEntry[] = [
	{cp: 0x0501, end: 'KOMI DE', template: [CL, S], cat: 'Ll'},
	{cp: 0x0500, end: 'KOMI DE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0503, end: 'KOMI DJE', template: [CL, S], cat: 'Ll'},
	{cp: 0x0502, end: 'KOMI DJE', template: [CL, C], cat: 'Lu'},
	{cp: 0x052B, end: 'DZZHE', template: [CL, S], cat: 'Ll'},
	{cp: 0x052A, end: 'DZZHE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0505, end: 'KOMI ZJE', template: [CL, S], cat: 'Ll'},
	{cp: 0x0504, end: 'KOMI ZJE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0511, end: 'REVERSED ZE', template: [CL, S], cat: 'Ll'},
	{cp: 0x0510, end: 'REVERSED ZE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0507, end: 'KOMI DZJE', template: [CL, S], cat: 'Ll'},
	{cp: 0x0506, end: 'KOMI DZJE', template: [CL, C], cat: 'Lu'},
	{cp: 0x051F, end: 'ALEUT KA', template: [CL, S], cat: 'Ll'},
	{cp: 0x051E, end: 'ALEUT KA', template: [CL, C], cat: 'Lu'},
	{cp: 0x051B, end: 'QA', template: [CL, S], cat: 'Ll'},
	{cp: 0x051A, end: 'QA', template: [CL, C], cat: 'Lu'},
	{cp: 0x052F, template: [CL, S, 'EL', DESCENDER], cat: 'Ll'},
	{cp: 0x052E, template: [CL, C, 'EL', DESCENDER], cat: 'Lu'},
	{cp: 0x0513, end: 'EL WITH HOOK', template: [CL, S], cat: 'Ll'},
	{cp: 0x0512, end: 'EL WITH HOOK', template: [CL, C], cat: 'Lu'},
	{cp: 0x0521, end: 'EL WITH MIDDLE HOOK', template: [CL, S], cat: 'Ll'},
	{cp: 0x0520, end: 'EL WITH MIDDLE HOOK', template: [CL, C], cat: 'Lu'},
	{cp: 0x0509, end: 'KOMI LJE', template: [CL, S], cat: 'Ll'},
	{cp: 0x0508, end: 'KOMI LJE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0515, end: 'LHA', template: [CL, S], cat: 'Ll'},
	{cp: 0x0514, end: 'LHA', template: [CL, C], cat: 'Lu'},
	{cp: 0x0529, end: 'EN WITH LEFT HOOK', template: [CL, S], cat: 'Ll'},
	{cp: 0x0528, end: 'EN WITH LEFT HOOK', template: [CL, C], cat: 'Lu'},
	{cp: 0x0523, end: 'EN WITH MIDDLE HOOK', template: [CL, S], cat: 'Ll'},
	{cp: 0x0522, end: 'EN WITH MIDDLE HOOK', template: [CL, C], cat: 'Lu'},
	{cp: 0x050B, end: 'KOMI NJE', template: [CL, S], cat: 'Ll'},
	{cp: 0x050A, end: 'KOMI NJE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0525, template: [CL, S, 'PE', DESCENDER], cat: 'Ll'},
	{cp: 0x0524, template: [CL, C, 'PE', DESCENDER], cat: 'Lu'},
	{cp: 0x0517, end: 'RHA', template: [CL, S], cat: 'Ll'},
	{cp: 0x0516, end: 'RHA', template: [CL, C], cat: 'Lu'},
	{cp: 0x050D, end: 'KOMI SJE', template: [CL, S], cat: 'Ll'},
	{cp: 0x050C, end: 'KOMI SJE', template: [CL, C], cat: 'Lu'},
	{cp: 0x050F, end: 'KOMI TJE', template: [CL, S], cat: 'Ll'},
	{cp: 0x050E, end: 'KOMI TJE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0527, template: [CL, S, 'SHHA', DESCENDER], cat: 'Ll'},
	{cp: 0x0526, template: [CL, C, 'SHHA', DESCENDER], cat: 'Lu'},
	{cp: 0x052D, end: 'DCHE', template: [CL, S], cat: 'Ll'},
	{cp: 0x052C, end: 'DCHE', template: [CL, C], cat: 'Lu'},
	{cp: 0x0519, end: 'YAE', template: [CL, S], cat: 'Ll'},
	{cp: 0x0518, end: 'YAE', template: [CL, C], cat: 'Lu'},
	{cp: 0x051D, end: 'WE', template: [CL, S], cat: 'Ll'},
	{cp: 0x051C, end: 'WE', template: [CL, C], cat: 'Lu'},
];

export const characters: Record<string, NameEntry[]> = {cyrillic};
