// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

const block_elements: NameEntry[] = [
	{cp: 0x2580, name: 'UPPER HALF BLOCK', cat: 'misc'},
	{cp: 0x2581, name: 'LOWER ONE EIGHTH BLOCK', cat: 'misc'},
	{cp: 0x2582, name: 'LOWER ONE QUARTER BLOCK', cat: 'misc'},
	{cp: 0x2583, name: 'LOWER THREE EIGHTHS BLOCK', cat: 'misc'},
	{cp: 0x2584, name: 'LOWER HALF BLOCK', cat: 'misc'},
	{cp: 0x2585, name: 'LOWER FIVE EIGHTHS BLOCK', cat: 'misc'},
	{cp: 0x2586, name: 'LOWER THREE QUARTERS BLOCK', cat: 'misc'},
	{cp: 0x2587, name: 'LOWER SEVEN EIGHTHS BLOCK', cat: 'misc'},
	{cp: 0x2588, name: 'FULL BLOCK', cat: 'misc'},
	{cp: 0x2589, name: 'LEFT SEVEN EIGHTHS BLOCK', cat: 'misc'},
	{cp: 0x258A, name: 'LEFT THREE QUARTERS BLOCK', cat: 'misc'},
	{cp: 0x258B, name: 'LEFT FIVE EIGHTHS BLOCK', cat: 'misc'},
	{cp: 0x258C, name: 'LEFT HALF BLOCK', cat: 'misc'},
	{cp: 0x258D, name: 'LEFT THREE EIGHTHS BLOCK', cat: 'misc'},
	{cp: 0x258E, name: 'LEFT ONE QUARTER BLOCK', cat: 'misc'},
	{cp: 0x258F, name: 'LEFT ONE EIGHTH BLOCK', cat: 'misc'},
	{cp: 0x2590, name: 'RIGHT HALF BLOCK', cat: 'misc'},
	{cp: 0x2591, name: 'LIGHT SHADE', cat: 'misc'},
	{cp: 0x2592, name: 'MEDIUM SHADE', cat: 'misc'},
	{cp: 0x2593, name: 'DARK SHADE', cat: 'misc'},
	{cp: 0x2594, name: 'UPPER ONE EIGHTH BLOCK', cat: 'misc'},
	{cp: 0x2595, name: 'RIGHT ONE EIGHTH BLOCK', cat: 'misc'},
	{cp: 0x2596, name: 'QUADRANT LOWER LEFT', cat: 'misc'},
	{cp: 0x2597, name: 'QUADRANT LOWER RIGHT', cat: 'misc'},
	{cp: 0x2598, name: 'QUADRANT UPPER LEFT', cat: 'misc'},
	{cp: 0x2599, name: 'QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT', cat: 'misc'},
	{cp: 0x259A, name: 'QUADRANT UPPER LEFT AND LOWER RIGHT', cat: 'misc'},
	{cp: 0x259B, name: 'QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT', cat: 'misc'},
	{cp: 0x259C, name: 'QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT', cat: 'misc'},
	{cp: 0x259D, name: 'QUADRANT UPPER RIGHT', cat: 'misc'},
	{cp: 0x259E, name: 'QUADRANT UPPER RIGHT AND LOWER LEFT', cat: 'misc'},
	{cp: 0x259F, name: 'QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT', cat: 'misc'},
];

export const characters: Record<string, NameEntry[]> = {block_elements};
