// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

import {_, S} from '../constants/strings';
import {LL} from '../constants/strings';

const latin_extendedg: NameEntry[] = [
	{cp: 0x1DF00, end: 'FENG DIGRAPH WITH TRILL', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF01, end: 'REVERSED SCRIPT G', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF02, end: 'SMALL CAPITAL TURNED G', template: [LL, _], cat: 'latin'},
	{cp: 0x1DF03, end: 'REVERSED K', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF04, end: 'SMALL CAPITAL L WITH BELT', template: [LL, _], cat: 'latin'},
	{cp: 0x1DF05, end: 'LEZH WITH RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF06, end: 'TURNED Y WITH BELT', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF07, end: 'REVERSED ENG', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF08, end: 'TURNED R WITH LONG LEG AND RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF09, end: 'T WITH HOOK AND RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF0A, end: 'RETROFLEX CLICK WITH RETROFLEX HOOK', template: [LL, _], cat: 'latin'},
	{cp: 0x1DF0B, end: 'ESH WITH DOUBLE BAR', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF0C, end: 'ESH WITH DOUBLE BAR AND CURL', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF0D, end: 'TURNED T WITH CURL', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF0E, end: 'INVERTED GLOTTAL STOP WITH CURL', template: [LL, _], cat: 'latin'},
	{cp: 0x1DF0F, end: 'STRETCHED C WITH CURL', template: [LL, _], cat: 'latin'},
	{cp: 0x1DF10, end: 'SMALL CAPITAL TURNED K', template: [LL, _], cat: 'latin'},
	{cp: 0x1DF11, end: 'L WITH FISHHOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF12, end: 'DEZH DIGRAPH WITH PALATAL HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF13, end: 'L WITH BELT AND PALATAL HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF14, end: 'ENG WITH PALATAL HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF15, end: 'TURNED R WITH PALATAL HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF16, end: 'R WITH FISHHOOK AND PALATAL HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF17, end: 'TESH DIGRAPH WITH PALATAL HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF18, end: 'EZH WITH PALATAL HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF19, end: 'DEZH DIGRAPH WITH RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF1A, end: 'I WITH STROKE AND RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF1B, end: 'O WITH RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF1C, end: 'TESH DIGRAPH WITH RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF1D, end: 'C WITH RETROFLEX HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF1E, end: 'S WITH CURL', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF25, end: 'D WITH MID-HEIGHT LEFT HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF26, end: 'L WITH MID-HEIGHT LEFT HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF27, end: 'N WITH MID-HEIGHT LEFT HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF28, end: 'R WITH MID-HEIGHT LEFT HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF29, end: 'S WITH MID-HEIGHT LEFT HOOK', template: [LL, S], cat: 'latin'},
	{cp: 0x1DF2A, end: 'T WITH MID-HEIGHT LEFT HOOK', template: [LL, S], cat: 'latin'},
];

export const characters: Record<string, NameEntry[]> = {latin_extendedg};
