// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

import {ML} from '../constants/strings';

const modifier_tone_letters: NameEntry[] = [
	{cp: 0xA700, template: [ML, 'CHINESE TONE YIN PING'], cat: 'Sk'},
	{cp: 0xA701, template: [ML, 'CHINESE TONE YANG PING'], cat: 'Sk'},
	{cp: 0xA702, template: [ML, 'CHINESE TONE YIN SHANG'], cat: 'Sk'},
	{cp: 0xA703, template: [ML, 'CHINESE TONE YANG SHANG'], cat: 'Sk'},
	{cp: 0xA704, template: [ML, 'CHINESE TONE YIN QU'], cat: 'Sk'},
	{cp: 0xA705, template: [ML, 'CHINESE TONE YANG QU'], cat: 'Sk'},
	{cp: 0xA706, template: [ML, 'CHINESE TONE YIN RU'], cat: 'Sk'},
	{cp: 0xA707, template: [ML, 'CHINESE TONE YANG RU'], cat: 'Sk'},
	{cp: 0xA708, template: [ML, 'EXTRA-HIGH DOTTED TONE BAR'], cat: 'Sk'},
	{cp: 0xA709, template: [ML, 'HIGH DOTTED TONE BAR'], cat: 'Sk'},
	{cp: 0xA70A, template: [ML, 'MID DOTTED TONE BAR'], cat: 'Sk'},
	{cp: 0xA70B, template: [ML, 'LOW DOTTED TONE BAR'], cat: 'Sk'},
	{cp: 0xA70C, template: [ML, 'EXTRA-LOW DOTTED TONE BAR'], cat: 'Sk'},
	{cp: 0xA70D, template: [ML, 'EXTRA-HIGH DOTTED LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA70E, template: [ML, 'HIGH DOTTED LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA70F, template: [ML, 'MID DOTTED LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA710, template: [ML, 'LOW DOTTED LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA711, template: [ML, 'EXTRA-LOW DOTTED LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA712, template: [ML, 'EXTRA-HIGH LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA713, template: [ML, 'HIGH LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA714, template: [ML, 'MID LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA715, template: [ML, 'LOW LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA716, template: [ML, 'EXTRA-LOW LEFT-STEM TONE BAR'], cat: 'Sk'},
	{cp: 0xA717, template: [ML, 'DOT VERTICAL BAR'], cat: 'Lm'},
	{cp: 0xA718, template: [ML, 'DOT SLASH'], cat: 'Lm'},
	{cp: 0xA719, template: [ML, 'DOT HORIZONTAL BAR'], cat: 'Lm'},
	{cp: 0xA71A, template: [ML, 'LOWER RIGHT CORNER ANGLE'], cat: 'Lm'},
	{cp: 0xA71B, template: [ML, 'RAISED UP ARROW'], cat: 'Lm'},
	{cp: 0xA71C, template: [ML, 'RAISED DOWN ARROW'], cat: 'Lm'},
	{cp: 0xA71D, template: [ML, 'RAISED EXCLAMATION MARK'], cat: 'Lm'},
	{cp: 0xA71E, template: [ML, 'RAISED INVERTED EXCLAMATION MARK'], cat: 'Lm'},
	{cp: 0xA71F, template: [ML, 'LOW INVERTED EXCLAMATION MARK'], cat: 'Lm'},
];

export const characters: Record<string, NameEntry[]> = {modifier_tone_letters};
