// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

const arabic: NameEntry[] = [
	{cp: 0x10EFB, name: 'ARABIC SMALL LOW NOON', cat: 'Mn'},
	{cp: 0x10EFD, name: 'ARABIC SMALL LOW WORD SAKTA', cat: 'Mn'},
	{cp: 0x10EFE, name: 'ARABIC SMALL LOW WORD QASR', cat: 'Mn'},
	{cp: 0x10EFF, name: 'ARABIC SMALL LOW WORD MADDA', cat: 'Mn'},
	{cp: 0x10EFC, name: 'ARABIC COMBINING ALEF OVERLAY', cat: 'Mn'},
	{cp: 0x10EFA, name: 'ARABIC DOUBLE VERTICAL BAR BELOW', cat: 'Mn'},
	{cp: 0x10ED0, name: 'ARABIC BIBLICAL END OF VERSE', cat: 'Po'},
	{cp: 0x10ED1, name: 'ARABIC LIGATURE ALAYHAA AS-SALAATU WAS-SALAAM', cat: 'So'},
	{cp: 0x10ED2, name: 'ARABIC LIGATURE ALAYHIM AS-SALAATU WAS-SALAAM', cat: 'So'},
	{cp: 0x10ED3, name: 'ARABIC LIGATURE ALAYHIMAA AS-SALAATU WAS-SALAAM', cat: 'So'},
	{cp: 0x10ED4, name: 'ARABIC LIGATURE QADDASA ALLAAHU SIRRAH', cat: 'So'},
	{cp: 0x10ED5, name: 'ARABIC LIGATURE QUDDISA SIRRUHUM', cat: 'So'},
	{cp: 0x10ED6, name: 'ARABIC LIGATURE QUDDISA SIRRUHUMAA', cat: 'So'},
	{cp: 0x10ED7, name: 'ARABIC LIGATURE QUDDISAT ASRAARUHUM', cat: 'So'},
	{cp: 0x10ED8, name: 'ARABIC LIGATURE NAWWARA ALLAAHU MARQADAH', cat: 'So'},
	{cp: 0x10EC2, name: 'ARABIC LETTER DAL WITH TWO DOTS VERTICALLY BELOW', cat: 'Lo'},
	{cp: 0x10EC3, name: 'ARABIC LETTER TAH WITH TWO DOTS VERTICALLY BELOW', cat: 'Lo'},
	{cp: 0x10EC4, name: 'ARABIC LETTER KAF WITH TWO DOTS VERTICALLY BELOW', cat: 'Lo'},
	{cp: 0x10EC6, name: 'ARABIC LETTER THIN NOON', cat: 'Lo'},
	{cp: 0x10EC5, name: 'ARABIC SMALL YEH BARREE WITH TWO DOTS BELOW', cat: 'Lm'},
	{cp: 0x10EC7, name: 'ARABIC LETTER YEH WITH FOUR DOTS BELOW', cat: 'Lo'},
];

export const characters: Record<string, NameEntry[]> = {arabic};
