// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

const georgian: NameEntry[] = [
	{cp: 0x2D00, name: 'GEORGIAN SMALL LETTER AN', cat: 'Ll'},
	{cp: 0x2D01, name: 'GEORGIAN SMALL LETTER BAN', cat: 'Ll'},
	{cp: 0x2D02, name: 'GEORGIAN SMALL LETTER GAN', cat: 'Ll'},
	{cp: 0x2D03, name: 'GEORGIAN SMALL LETTER DON', cat: 'Ll'},
	{cp: 0x2D04, name: 'GEORGIAN SMALL LETTER EN', cat: 'Ll'},
	{cp: 0x2D05, name: 'GEORGIAN SMALL LETTER VIN', cat: 'Ll'},
	{cp: 0x2D06, name: 'GEORGIAN SMALL LETTER ZEN', cat: 'Ll'},
	{cp: 0x2D21, name: 'GEORGIAN SMALL LETTER HE', cat: 'Ll'},
	{cp: 0x2D07, name: 'GEORGIAN SMALL LETTER TAN', cat: 'Ll'},
	{cp: 0x2D08, name: 'GEORGIAN SMALL LETTER IN', cat: 'Ll'},
	{cp: 0x2D09, name: 'GEORGIAN SMALL LETTER KAN', cat: 'Ll'},
	{cp: 0x2D0A, name: 'GEORGIAN SMALL LETTER LAS', cat: 'Ll'},
	{cp: 0x2D0B, name: 'GEORGIAN SMALL LETTER MAN', cat: 'Ll'},
	{cp: 0x2D0C, name: 'GEORGIAN SMALL LETTER NAR', cat: 'Ll'},
	{cp: 0x2D22, name: 'GEORGIAN SMALL LETTER HIE', cat: 'Ll'},
	{cp: 0x2D0D, name: 'GEORGIAN SMALL LETTER ON', cat: 'Ll'},
	{cp: 0x2D0E, name: 'GEORGIAN SMALL LETTER PAR', cat: 'Ll'},
	{cp: 0x2D0F, name: 'GEORGIAN SMALL LETTER ZHAR', cat: 'Ll'},
	{cp: 0x2D10, name: 'GEORGIAN SMALL LETTER RAE', cat: 'Ll'},
	{cp: 0x2D11, name: 'GEORGIAN SMALL LETTER SAN', cat: 'Ll'},
	{cp: 0x2D12, name: 'GEORGIAN SMALL LETTER TAR', cat: 'Ll'},
	{cp: 0x2D23, name: 'GEORGIAN SMALL LETTER WE', cat: 'Ll'},
	{cp: 0x2D13, name: 'GEORGIAN SMALL LETTER UN', cat: 'Ll'},
	{cp: 0x2D14, name: 'GEORGIAN SMALL LETTER PHAR', cat: 'Ll'},
	{cp: 0x2D15, name: 'GEORGIAN SMALL LETTER KHAR', cat: 'Ll'},
	{cp: 0x2D16, name: 'GEORGIAN SMALL LETTER GHAN', cat: 'Ll'},
	{cp: 0x2D17, name: 'GEORGIAN SMALL LETTER QAR', cat: 'Ll'},
	{cp: 0x2D18, name: 'GEORGIAN SMALL LETTER SHIN', cat: 'Ll'},
	{cp: 0x2D19, name: 'GEORGIAN SMALL LETTER CHIN', cat: 'Ll'},
	{cp: 0x2D1A, name: 'GEORGIAN SMALL LETTER CAN', cat: 'Ll'},
	{cp: 0x2D1B, name: 'GEORGIAN SMALL LETTER JIL', cat: 'Ll'},
	{cp: 0x2D1C, name: 'GEORGIAN SMALL LETTER CIL', cat: 'Ll'},
	{cp: 0x2D1D, name: 'GEORGIAN SMALL LETTER CHAR', cat: 'Ll'},
	{cp: 0x2D1E, name: 'GEORGIAN SMALL LETTER XAN', cat: 'Ll'},
	{cp: 0x2D24, name: 'GEORGIAN SMALL LETTER HAR', cat: 'Ll'},
	{cp: 0x2D1F, name: 'GEORGIAN SMALL LETTER JHAN', cat: 'Ll'},
	{cp: 0x2D20, name: 'GEORGIAN SMALL LETTER HAE', cat: 'Ll'},
	{cp: 0x2D25, name: 'GEORGIAN SMALL LETTER HOE', cat: 'Ll'},
	{cp: 0x2D27, name: 'GEORGIAN SMALL LETTER YN', cat: 'Ll'},
	{cp: 0x2D2D, name: 'GEORGIAN SMALL LETTER AEN', cat: 'Ll'},
];

export const characters: Record<string, NameEntry[]> = {georgian};
