// This file is auto-generated by scripts/generate-names.ts
// Do not edit this file directly.

import {NameEntry} from '../types';

const georgian: NameEntry[] = [
	{cp: 0x2D00, name: 'GEORGIAN SMALL LETTER AN'},
	{cp: 0x2D01, name: 'GEORGIAN SMALL LETTER BAN'},
	{cp: 0x2D02, name: 'GEORGIAN SMALL LETTER GAN'},
	{cp: 0x2D03, name: 'GEORGIAN SMALL LETTER DON'},
	{cp: 0x2D04, name: 'GEORGIAN SMALL LETTER EN'},
	{cp: 0x2D05, name: 'GEORGIAN SMALL LETTER VIN'},
	{cp: 0x2D06, name: 'GEORGIAN SMALL LETTER ZEN'},
	{cp: 0x2D07, name: 'GEORGIAN SMALL LETTER TAN'},
	{cp: 0x2D08, name: 'GEORGIAN SMALL LETTER IN'},
	{cp: 0x2D09, name: 'GEORGIAN SMALL LETTER KAN'},
	{cp: 0x2D0A, name: 'GEORGIAN SMALL LETTER LAS'},
	{cp: 0x2D0B, name: 'GEORGIAN SMALL LETTER MAN'},
	{cp: 0x2D0C, name: 'GEORGIAN SMALL LETTER NAR'},
	{cp: 0x2D0D, name: 'GEORGIAN SMALL LETTER ON'},
	{cp: 0x2D0E, name: 'GEORGIAN SMALL LETTER PAR'},
	{cp: 0x2D0F, name: 'GEORGIAN SMALL LETTER ZHAR'},
	{cp: 0x2D10, name: 'GEORGIAN SMALL LETTER RAE'},
	{cp: 0x2D11, name: 'GEORGIAN SMALL LETTER SAN'},
	{cp: 0x2D12, name: 'GEORGIAN SMALL LETTER TAR'},
	{cp: 0x2D13, name: 'GEORGIAN SMALL LETTER UN'},
	{cp: 0x2D14, name: 'GEORGIAN SMALL LETTER PHAR'},
	{cp: 0x2D15, name: 'GEORGIAN SMALL LETTER KHAR'},
	{cp: 0x2D16, name: 'GEORGIAN SMALL LETTER GHAN'},
	{cp: 0x2D17, name: 'GEORGIAN SMALL LETTER QAR'},
	{cp: 0x2D18, name: 'GEORGIAN SMALL LETTER SHIN'},
	{cp: 0x2D19, name: 'GEORGIAN SMALL LETTER CHIN'},
	{cp: 0x2D1A, name: 'GEORGIAN SMALL LETTER CAN'},
	{cp: 0x2D1B, name: 'GEORGIAN SMALL LETTER JIL'},
	{cp: 0x2D1C, name: 'GEORGIAN SMALL LETTER CIL'},
	{cp: 0x2D1D, name: 'GEORGIAN SMALL LETTER CHAR'},
	{cp: 0x2D1E, name: 'GEORGIAN SMALL LETTER XAN'},
	{cp: 0x2D1F, name: 'GEORGIAN SMALL LETTER JHAN'},
	{cp: 0x2D20, name: 'GEORGIAN SMALL LETTER HAE'},
	{cp: 0x2D21, name: 'GEORGIAN SMALL LETTER HE'},
	{cp: 0x2D22, name: 'GEORGIAN SMALL LETTER HIE'},
	{cp: 0x2D23, name: 'GEORGIAN SMALL LETTER WE'},
	{cp: 0x2D24, name: 'GEORGIAN SMALL LETTER HAR'},
	{cp: 0x2D25, name: 'GEORGIAN SMALL LETTER HOE'},
	{cp: 0x2D27, name: 'GEORGIAN SMALL LETTER YN'},
	{cp: 0x2D2D, name: 'GEORGIAN SMALL LETTER AEN'},
];

export const characters: Record<string, NameEntry[]> = {georgian};
